In [1]:
import argparse
import os
import pandas as pd
import pickle
import tensorflow as tf
import scipy.io as sc
import numpy as np
from sklearn import preprocessing
from scipy.signal import butter, lfilter
from xuejie import *


In [2]:
import argparse
import os
import pandas as pd
import pickle
import tensorflow as tf
import scipy.io as sc
import numpy as np
from sklearn import preprocessing
from scipy.signal import butter, lfilter
from xuejie import *


def one_hot(y_):
    '''
    # this function is used to transfer one column label to one hot label
    # Function to encode output labels from number indexes
    # e.g.: [[5], [0], [3]] --> [[0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0]]
    @return: one_hot_code
    '''
    y_ = y_.reshape(len(y_))
    y_ = y_.astype(int)
    n_values = np.max(y_) + 1
    return np.eye(n_values)[np.array(y_, dtype=np.int32)]


def butter_bandpass(lowcut, highcut, fs, order=5):
    '''
    extract the delta from the data
    @return: b,a
    '''
    nyq = 0.5 * fs
    low = lowcut / nyq
    high = highcut / nyq
    b, a = butter(order, [low, high], btype='band')
    return b, a

def butter_bandpass_filter(data, lowcut, highcut, fs, order=5):
    '''
    @return: y
    '''
    b, a = butter_bandpass(lowcut, highcut, fs, order=order)
    y = lfilter(b, a, data)
    return y

def data_1Dto2D(data, Y=10, X=11):

    '''

        :param data: change the 1D data to 2D data
        :param Y: the length of 2D
        :param X:  the width of 2D
        :return: 2D data
        '''
    data_2D = np.zeros([Y, X])
    data_2D[0] = ( 	   	 0, 	   0,  	   	 0, 	   0,    data[0],  data[1],  data[2], 	      0,  	     0, 	   0, 	 	 0)
    data_2D[1] = (	  	 0, 	   0,  	   	 0,         0,   data[3],        0,  data[4],         0, 	   	 0,   	   0, 	 	 0)
    data_2D[2] = (	  	 0, data[5],    data[6],  data[7],   data[8],  data[9], data[10], data[11],  data[12],  data[13], 	 	 0)
    data_2D[3] = (	  	 0, data[14],  data[15],  data[16],  data[17], data[18], data[19], data[20],  data[21],  data[22], 		 0)
    data_2D[4] = (       0, data[23],  data[24],  data[25],  data[26], data[27], data[28], data[29],  data[30],  data[31],       0)
    data_2D[5] = (	  	 0, data[32],  data[33],  data[34],  data[35], data[36], data[37], data[38],  data[39],  data[40], 		 0)
    data_2D[6] = (	  	 0, data[41],  data[42],  data[43],  data[44], data[45], data[46], data[47],  data[48],  data[49], 		 0)
    data_2D[7] = (	  	 0, 	   0,  data[50],  data[51],  data[52], data[53], data[54], data[55],  data[56], 	   0, 		 0)
    data_2D[8] = (	  	 0, 	   0, 	 	 0,   data[57],  data[58], data[59], data[60], data[61], 	   	 0, 	   0, 		 0)
    data_2D[9] = (	  	 0, 	   0, 	 	 0, 	     0, 	    0,        0, 		 0, 	   0, 	   	 0, 	   0, 		 0)
    #return shape:10*11
    return data_2D

def norm_dataset(dataset_1D):
    norm_dataset_1D = np.zeros([dataset_1D.shape[0], 62])
    for i in range(dataset_1D.shape[0]):
        norm_dataset_1D[i] = feature_normalize(dataset_1D[i])
    # return shape: m*64
    return norm_dataset_1D

def feature_normalize(data):
    mean = data[data.nonzero()].mean()
    sigma = data[data.nonzero()].std()
    data_normalized = data
    data_normalized[data_normalized.nonzero()] = (data_normalized[data_normalized.nonzero()] - mean)/sigma
    # return shape: 10*11
    return data_normalized

def dataset_1Dto2D(dataset_1D):
    dataset_2D = np.zeros([dataset_1D.shape[0], 10, 11])
    for i in range(dataset_1D.shape[0]):
         dataset_2D[i] = data_1Dto2D(dataset_1D[i])
    # return shape: m*10*11
    return dataset_2D

def norm_dataset_1Dto2D(dataset_1D):
    norm_dataset_2D = np.zeros([dataset_1D.shape[0], 10, 11])
    for i in range(dataset_1D.shape[0]):
        norm_dataset_2D[i] = feature_normalize(data_1Dto2D(dataset_1D[i]))
    # return shape: m*10*11
    return norm_dataset_2D

def windows(data, size):
    start = 0
    while ((start+size) < data.shape[0]):
        yield int(start), int(start + size)
        start += (size)

def segment_signal_without_transition(data, label, window_size):
    for (start, end) in windows(data, window_size):
        # print(data.shape)
        if((len(data[start:end]) == window_size) and (len(set(label))==1)):
            if(start == 0):
                segments = data[start:end]
                # labels = stats.mode(label[start:end])[0][0]
                labels_one = label[0]

            else:
                segments = np.vstack([segments, data[start:end]])
                labels_one = np.append(labels_one, label[0])
                # labels = np.append(labels, stats.mode(label[start:end])[0][0])

    print("the shape of segments is:", segments.shape)
    print("the shape of labels_one is:", labels_one.shape)
    return segments, labels_one

def get_a_student_eegs(student_data_path):
    '''
    @param mat_path:
    @return student_name:
    @return eegs:
    '''
    import scipy.io
    student_name = os.path.basename(student_data_path).replace('.mat', '')
    a_student_data = scipy.io.loadmat(student_data_path)
    eeg_keys = [i for i in a_student_data.keys() if i[0] != '_']
    #print(eeg_keys)
    eegs = []
    for eeg_key in eeg_keys:
        if get_label(eeg_key) in {3, 4, 7, 12, 15}: ##positive
            eegs.append(a_student_data[eeg_key])
    return eegs
# if get_label(eeg_key) in {1, 6, 9, 10, 14}:   ##positive
# if get_label(eeg_key) in {3, 4, 7, 12, 15}:  #negative emotion
# if get_label(eeg_key) in {2, 5, 8, 11, 13}:  #middle emotion

In [3]:
students_data_dir = './cat'
student_data_paths = get_student_data_paths('./cat')

labels = []
eg = []
i = 0
for student_data_path in student_data_paths:
	num = ''.join([x for x in student_data_path if x.isdigit()])
	temp = int(num)-1
	label = temp * np.ones((5))
	eegs = get_a_student_eegs(student_data_path = os.path.join(students_data_dir, student_data_path))
	labels.append(label)
	eg.append(eegs)

label_all = []

fs = 200
lowcut = 4
highcut = 40
# 四种波的频率范围


for i in range(len(eg)):
	for j in range(len(eg[i])):
		s = np.array(eg[i][j]) #s shape (62,47001)
		for q in range(62):
			print(s[q])
			s[q] = butter_bandpass_filter(s[q], lowcut, highcut, fs, order=5)
			print(s[q])
		eg[i][j] = s


#print('len(eg)', len(eg))


for i in range(len(eg)):
	for j in range(len(eg[i])):
		data_f1 = np.array(eg[i][j])
		data_f1 = np.transpose(data_f1)

		#x_all = preprocessing.scale(data_f1)
		x_all = norm_dataset(data_f1)
		#x_all = data_f1
		window_size = 200*5
		label = labels[i]
		seg_datas, s = segment_signal_without_transition(x_all, label, window_size)
		if len(label_all) == 0:

			label_all = s
			seg_data_all = seg_datas
		else:
			label_all = np.append(label_all, s)
			seg_data_all = np.vstack([seg_data_all, seg_datas])

print('len(label_all)', len(label_all))
print('seg_data_all', seg_data_all.shape)
D2_data = dataset_1Dto2D(seg_data_all)
print('D2_data.shape', D2_data.shape)
D3_data = np.reshape(D2_data, (len(label_all), 200*5, 10, 11))
print(D3_data.shape)

with open('./result/D3_data3_neg2.pkl', "wb") as fp:
	pickle.dump(D3_data, fp, protocol=4)
with open('./result/D3_label3_neg2.pkl', "wb") as fp:
	pickle.dump(label_all, fp)
print("over")

[ 54.65745926  62.52527237  73.31371307 ...  -1.22189522  -9.68575478
 -19.22249794]
[ 0.78924929  5.49853418 16.9802311  ... -3.33516048 -6.86257648
 -7.26679465]
[ 24.88493919  29.20627594  41.72325134 ... -13.50045204 -11.08646393
 -22.53055573]
[ 0.35933651  2.51409616  7.91355721 ... -5.19899373 -8.07789751
 -6.32932141]
[ 41.96166992  39.51787949  52.60109901 ... -25.18296242 -12.18914986
 -25.92802048]
[ 0.60592312  4.09882987 12.26953695 ... -6.84641487 -8.95603663
 -5.02201699]
[ 21.9643116   22.85838127  30.33876419 ...  -2.20537186 -16.95752144
 -21.72589302]
[ 0.31716288  2.17686269  6.64557426 ... -0.76323854 -5.37072468
 -7.35646258]
[ 31.1434269   25.06375313  35.85219383 ... -42.28949547 -20.17617226
 -10.46061516]
[ 0.44970856  2.98050071  8.70158237 ... -8.4061067  -7.07368858
 -1.67714182]
[ 39.75629807  21.45767212  28.01418304 ...  33.61701965 -36.23962402
 -22.02391624]
[  0.57407773   3.65261124   9.96568028 ...  10.11828408  -2.98720875
 -15.99391556]
[ 26.67307

[-0.07143696 -0.40778964 -0.72657685 ...  3.36224246  3.04350345
  1.005199  ]
[  -8.67247581   -5.84125519    5.7220459  ... -428.70640755 -426.26261711
 -418.6630249 ]
[-0.12522985 -0.81354094 -2.10062692 ...  0.2587098   0.58684121
  0.21096491]
[-3.06963921 -1.90734863  3.7252903  ... -5.84125519 -8.55326653
 -4.58955765]
[-0.04432534 -0.28564144 -0.70550586 ...  1.05103569  1.79407906
  1.70582006]
[ 9.35792923 11.26527786 11.59310341 ... 43.86901855 43.86901855
 46.22340202]
[0.13512774 0.94949725 2.94045637 ... 0.40145119 1.74909285 2.54651036]
[  5.27501106   5.81145287   4.61935997 ... -33.97464752 -36.38863564
 -33.25939178]
[ 0.07617073  0.52744709  1.58456091 ... -0.4163021  -0.06213595
  1.02526995]
[  3.78489494   3.09944153   3.24845314 ... -27.00090408 -30.90500832
 -27.20952034]
[ 0.05465358  0.36299485  1.04599459 ... -2.76860368 -2.75995395
 -0.81900188]
[ -4.85777855  -7.86781311  -9.03010368 ... -42.7365303  -47.62411118
 -41.24641418]
[-0.07014593 -0.52205928 -1.7

[-0.18203514 -1.14258784 -3.09527867 ...  5.86552315  4.20663152
  2.93084551]
[-5.51342964  1.37090683 -4.50015068 ... -1.4603138  -6.04987144
 -3.66568565]
[-0.07961348 -0.44378096 -1.02545541 ...  6.47947724  5.12480537
  4.53557039]
[-19.04368401 -14.21570778 -18.35823059 ...  -1.63912773  -6.34789467
  -3.12924385]
[-0.27498926 -1.8064928  -5.1760363  ...  5.83501722  6.66253189
  7.15434945]
[ -5.48362732  -0.77486038  -3.03983688 ...  -4.55975533 -11.86132431
  -6.67572021]
[-0.07918313 -0.47225984 -1.17897283 ...  5.94694114  5.23104748
  4.87894638]
[-12.18914986  -4.47034836  -8.07642937 ...  -5.63263893 -12.27855682
  -7.42077827]
[-0.17601034 -1.08943195 -2.87075657 ...  4.17960245  3.46046238
  3.39763924]
[-19.6993351   -7.59959221  -9.00030136 ...  -0.32782555  -4.41074371
  -0.68545341]
[-0.2844568  -1.76608467 -4.61254246 ...  3.63296558  1.46562912
 -0.26821599]
[-8.88109207 -1.40070915 -5.00679016 ... -0.77486038 -3.96370888
  0.95367432]
[-0.12824225 -0.76696056 -1.

[-0.11705333 -0.68502585 -1.83879611 ...  4.66236065  2.42660939
 -0.59017967]
[ -3.15904617  -2.50339508 -10.04338264 ... -16.21246338  -2.56299973
  -3.15904617]
[-0.04561637 -0.30176577 -0.97188524 ... -0.92320386 -2.91673885
 -4.51640494]
[ 2.23517418  1.63912773 -3.7252903  ... -7.1823597   2.32458115
  3.7252903 ]
[ 0.03227573  0.21160539  0.52013857 ... -3.01873171 -4.71868866
 -5.16381386]
[ 7.53998756  7.53998756  5.36441803 ... -2.17556953  2.56299973
  6.37769699]
[ 0.10887681  0.74284933  2.18258323 ... -3.16910885 -4.04808768
 -4.0231379 ]
[10.43081284  7.30156898  6.64591789 ...  3.81469727  6.16908073
 10.43081284]
[ 0.15062009  0.98247115  2.74507876 ... -3.81040283 -3.52135839
 -3.6971392 ]
[6.55651093 0.8046627  0.98347664 ... 4.82797623 5.54323196 9.00030136]
[ 0.09467549  0.56289972  1.36111842 ... -2.92022376 -3.31287476
 -3.83745797]
[ 0.         -8.64267349 -5.453825   ... 10.55002213  9.41753387
 10.22219658]
[ 0.         -0.12479951 -0.80544066 ... -2.7013431  

[-0.16998553 -1.18603546 -3.54408051 ... -3.17142461 -3.03470026
 -2.63701662]
[ 7.06315041  4.73856926 10.2519989  ... 11.20567322 11.11626625
  8.94069672]
[ 0.10199132  0.66230395  1.92457531 ... -3.96583102 -3.28717498
 -2.47994343]
[26.61347389 16.65949821 15.437603   ... 22.79877663 21.4278698
 16.57009125]
[ 0.38429641  2.47825928  6.8163037  ... -2.51792408 -3.14261916
 -3.07373682]
[ -9.08970833  -9.05990601 -12.30835915 ...   2.08616257  -1.25169754
  -2.59280205]
[-0.13125465 -0.89509948 -2.71302054 ... -3.4220206  -3.6485885
 -2.04595014]
[-25.45118332 -28.13339233 -29.38508987 ...   1.60932541   0.11920929
   0.92387199]
[-0.36751303 -2.54621439 -7.75566717 ... -1.52532616 -3.63468119
 -4.67882125]
[-21.87490463 -23.93126488 -22.5007534  ...  -2.44379044  -4.7981739
  -3.1888485 ]
[-0.31587185 -2.18483758 -6.6051591  ... -0.33264551 -3.01397748
 -4.4228555 ]
[-22.61996269 -25.45118332 -19.37150955 ...  -1.81794167  -3.87430191
  -1.37090683]
[-0.32663043 -2.26943059 -6.833

[ -0.10070029  -0.63197831  -1.84188625 ...  -9.15406128 -10.23386112
  -9.08892606]
[13.26203346 17.76218414  6.43730164 ... 45.21012306 48.1903553
 46.1935997 ]
[ 0.19150269  1.37157451  4.17401697 ... -7.37851627 -8.12337535
 -7.13367219]
[301.21207237 304.34131622 305.05657196 ... -15.34819603 -10.01358032
 -14.12630081]
[ 4.34947794 29.7209891  88.76479369 ... -6.7939656  -0.54399035
  6.41693913]
[172.13821411 178.15828323 177.83045769 ...   7.48038292  13.38124275
   6.73532486]
[ 2.48566187 17.04620887 51.13403938 ... -6.83675794 -3.61092818
  1.91094348]
[221.49085999 230.13353348 227.68974304 ...   3.33786011   8.49366188
   9.62615013]
[ 3.19831009 21.94636559 65.85349248 ... -6.75325305 -5.1855769
 -0.92843076]
[121.95110321 125.7956028  124.27568436 ...  -8.28504562  -7.39097595
  -9.59634781]
[ 1.76096406 12.07029473 36.16583318 ... -6.29353965 -0.40165973
  6.10141867]
[ 98.58608246 109.46393013 104.78496552 ...  -0.38743019   2.41398811
   7.27176666]
[ 1.42357505  9.86

[ -1.07887021  -7.35880983 -21.79707816 ...  -1.13182187   3.00171631
   4.43807986]
[-44.91209984 -57.30986595 -42.79613495 ...  18.7754631   16.09325409
  15.46740532]
[ -0.64852709  -4.60382092 -14.19959572 ...   4.08635153   6.73484874
   5.63667018]
[-47.05786705 -59.09800529 -45.26972771 ...   9.50694084   8.19563866
   5.39422035]
[ -0.67951179  -4.81006057 -14.80433031 ...   2.67015194   3.6345756
   3.1880329 ]
[-49.08442497 -58.26354027 -49.29304123 ...   3.51667404   4.47034836
   0.2682209 ]
[ -0.70877512  -4.96840673 -15.18767128 ...   2.71271634   3.2527196
   3.36097854]
[-63.6279583  -70.86992264 -65.356493   ...  -5.12599945  -4.05311584
  -7.59959221]
[ -0.91878257  -6.37328215 -19.31721936 ...   1.09338996   1.96629736
   3.37443085]
[-61.15436554 -63.21072578 -61.12456322 ...  -3.93390656  -3.06963921
  -6.22868538]
[ -0.88306409  -6.05470089 -18.12948494 ...  -1.42648036   0.53496137
   3.52599179]
[-48.07114601 -46.58102989 -46.40221596 ...   1.04308128   0.715255

[ 0.25002935  1.66072488  4.8289552  ...  0.54682855 -1.59286553
 -3.52036012]
[ 2.56299973  0.77486038  4.94718552 ... 19.28210258 17.49396324
 22.70936966]
[ 0.03700951  0.22668946  0.63666263 ... -0.9526182  -3.54776966
 -4.479107  ]
[ 2.95042992  1.4603138   5.96046448 ... 21.54707909 17.58337021
 18.89467239]
[ 0.04260397  0.26916302  0.7845208  ... -0.02370074 -2.00659915
 -3.35319167]
[ 4.7981739   5.21540642  8.13603401 ... 22.91798592 14.513731
 14.54353333]
[ 0.06928524  0.4787471   1.49218791 ...  1.95828888  0.14214829
 -2.16894313]
[ 4.58955765  5.453825    5.66244125 ... 39.01124001 28.87845039
 27.44793892]
[ 0.06627284  0.46464911  1.43581226 ...  2.84472421  1.08368378
 -1.65100816]
[-5.81145287e+00 -8.52346420e+00  2.98023224e-02 ...  3.36170197e+01
  2.09510326e+01  2.51233578e+01]
[-0.08391691 -0.61171308 -1.85012375 ...  2.74742423  0.52943238
 -2.34522915]
[37.37211227 18.95427704 19.1628933  ... 27.56714821 23.4246254
 31.88848495]
[ 0.53965028  3.4159968   9.162

[ -5.63263893  11.89112663   4.38094139 ... -62.31665611 -39.21985626
 -43.27297211]
[-0.08133485 -0.30189312 -0.03591788 ... 16.80513657 15.42217917
  1.13195552]
[ -2.68220901  16.71910286   7.15255737 ... -56.08797073 -59.69405174
 -72.80707359]
[-0.03873088  0.01589867  0.98571388 ...  5.64061411  8.78831869
  7.29957652]
[ -5.84125519  -6.10947609  -5.12599945 ... -34.03425217 -32.60374069
 -16.27206802]
[-0.08434725 -0.57936111 -1.72741649 ...  6.64002406  7.39976494
  7.70115569]
[ 13.91768456  15.88463783  20.53380013 ... -31.97789192 -31.02421761
 -26.82209015]
[0.20097024 1.39959093 4.34762859 ... 2.99785375 3.43282117 4.13842755]
[  6.97374344   7.53998756   9.68575478 ... -23.84185791 -24.64652061
 -21.6960907 ]
[0.10070029 0.69523875 2.13450144 ... 2.17568523 1.78462743 1.8845608 ]
[ -0.62584877  -0.14901161   1.01327896 ... -28.01418304 -28.28240395
 -28.64003181]
[-0.00903721 -0.05477394 -0.12000861 ...  0.92620408  0.70335745
  0.29508845]
[ 1.60932541 -6.64591789 -7.92

[-0.47940224 -3.29670657 -9.90840996 ... -1.57728049 -1.28850476
 -1.1871906 ]
[-33.19978714 -29.26588058 -34.2130661  ...   0.8046627    2.59280205
   2.23517418]
[-0.47940224 -3.21408069 -9.4324566  ... -2.72471062 -3.7342753
 -4.71626597]
[-23.81205559 -18.47743988 -32.45472908 ...  -1.10268593   8.70227814
   4.20212746]
[-0.34384415 -2.2689631  -6.66829177 ... -1.06443935 -3.76267378
 -5.9529623 ]
[-30.01093864 -20.83182335 -51.31959915 ... -12.93420792   1.37090683
   7.36117363]
[-0.43335552 -2.82417082 -8.3481409  ...  1.29930381 -1.31867824
 -6.84777259]
[-20.17617226 -34.60049629 -47.14727402 ...  13.41104507   2.29477882
  17.10653305]
[-0.29134229 -2.19606867 -7.52669188 ... -3.15923524  2.12068603
  4.37152232]
[-15.22898674 -23.63324165 -25.03395081 ...   1.22189522   1.81794167
   4.50015068]
[-0.21990534 -1.62173624 -5.31997565 ... -2.18123627 -0.79806054
  0.28690263]
[-15.437603   -23.75245094 -25.51078796 ...   0.35762787   2.44379044
   4.58955765]
[-0.22291774 -1.6

[0.12609053 0.84480351 2.2642509  ... 5.9682454  6.85588892 6.02901531]
[11.80171967  6.88433647 -4.08291817 ... 10.16259193 12.48717308
  6.22868538]
[0.17041588 1.09171407 2.82255538 ... 3.25101598 8.82281257 9.62882014]
[ 7.09295273  5.7220459  -4.35113907 ...  1.7285347  -1.87754631
 -4.08291817]
[ 0.10242166  0.6790111   1.80221407 ...  2.99247253  8.85266023
 10.05323157]
[ 4.23192978  2.50339508 -9.29832458 ...  4.20212746  7.80820847
  3.9935112 ]
[0.06110872 0.3919753  0.901926   ... 6.25111828 8.79251707 7.74299096]
[-25.00414848 -17.85159111 -18.5072422  ... -13.4408474  -16.15285873
 -15.13957977]
[-0.36105788 -2.36015871 -6.64686168 ... -9.76326878 -8.41170132
 -7.61808194]
[-19.66953278 -13.4408474  -12.04013824 ... -19.10328865 -19.01388168
 -20.98083496]
[-0.28402646 -1.8479261  -5.14176341 ... -6.31361447 -5.38286752
 -4.17556526]
[-10.69903374  -9.80496407  -8.76188278 ...   9.77516174   7.1823597
   6.16908073]
[-0.15449318 -1.04117235 -3.03845539 ... -4.11510891 -4.

[ -0.60248037  -3.96732444 -11.60499567 ...  -0.01914482  -0.37877684
  -3.21925503]
[-31.62026405 -38.77282143 -81.50935173 ...  27.12011337  19.93775368
  12.93420792]
[ -0.45659405  -3.21855167 -10.60658243 ...  10.50495051   2.02759495
  -5.45034562]
[-36.26942635 -35.31575203 -29.29568291 ...   1.93715096   0.8046627
  -0.17881393]
[ -0.52372758  -3.55953983 -10.46905774 ...  -5.06023101  -4.47652984
  -1.6229398 ]
[-12.36796379 -11.59310341  -8.49366188 ...  20.59340477  19.07348633
  19.37150955]
[-0.1785924  -1.20731887 -3.51056132 ... -1.33168856 -0.76304488
  0.46622309]
[-15.76542854 -14.33491707 -13.32163811 ...  -7.36117363  -7.9870224
  -9.29832458]
[-0.22765151 -1.53257395 -4.47370162 ... -0.44573514 -0.34507699
 -0.05655194]
[-10.72883606  -9.00030136  -8.55326653 ...  -0.44703484  -1.96695328
  -1.78813934]
[-0.15492352 -1.03205891 -2.97360066 ...  0.2145979  -0.24194294
 -0.87677539]
[-11.89112663  -7.86781311  -7.12275505 ...   2.8014183    2.95042992
   2.5331974 ]


[ 0.12307813  0.90472453  2.86222442 ... -3.61643311 -1.61226053
 -4.04841988]
[  1.10268593   4.67896461  -0.59604645 ... -44.37565804 -48.96521568
 -47.44529724]
[ 0.0159227   0.16027922  0.59995518 ... -9.3184867  -6.48944953
 -4.3564854 ]
[ -9.32812691  -3.39746475  -5.57303429 ... -22.02391624 -19.84834671
 -21.48747444]
[-0.1346974  -0.83338085 -2.1861757  ... -9.92380085 -3.79071067
 -0.75545907]
[ -9.03010368  -3.87430191  -6.10947609 ... -21.27885818 -20.05696297
 -21.24905586]
[ -0.13039397  -0.81520814  -2.17586682 ... -10.00629224  -3.9019967
  -0.6831839 ]
[-14.27531242 -10.16259193 -11.11626625 ... -26.67307854 -23.9610672
 -25.30217171]
[ -0.20613436  -1.3470349   -3.80030049 ... -10.05673141  -4.44959498
  -1.40105736]
[ -5.36441803   0.71525574  -7.33137131 ... -35.37535667 -38.86222839
 -32.09710121]
[-0.07746176 -0.44071941 -1.09239196 ... -5.615288   -3.84729328
 -6.04383564]
[ -5.93066216   0.56624413  -8.49366188 ... -35.10713577 -38.26618195
 -32.39512444]
[-0.08

[-0.32017528 -2.31059607 -7.14552618 ...  1.48768874  2.64014427
  6.02676086]
[ 31.1434269   32.60374069  37.37211227 ... -24.08027649 -20.44439316
 -18.80526543]
[  0.44970856   3.08937752   9.35750239 ...  -8.67519205 -13.23796618
 -12.38793123]
[ -5.21540642  -2.8014183   -0.38743019 ... -24.08027649 -14.2455101
 -16.62969589]
[-0.07531005 -0.47897079 -1.25873471 ...  3.53096554  2.50217902
  2.27961273]
[-31.23283386 -28.72943878 -25.62999725 ...  -3.75509262   3.33786011
   3.27825546]
[-0.45099959 -3.04095038 -8.87963503 ... -0.47095988 -1.15594015
 -0.38663205]
[-27.77576447 -23.06699753 -21.4278698  ... -22.79877663 -17.31514931
 -16.42107964]
[-0.40107979 -2.66851004 -7.66833192 ... -2.17125175 -1.52662212
  0.60464265]
[ -6.13927841  -3.93390656  -0.95367432 ... -24.2292881  -18.80526543
 -17.94099808]
[-0.08865068 -0.57300426 -1.54239175 ... -3.83401327 -3.30557528
 -0.92864131]
[-22.32193947 -21.39806747 -19.58012581 ... -26.91149712 -20.38478851
 -20.2357769 ]
[-0.322327 

[ -0.02237784  -0.18237417  -0.63139537 ... -20.03768709 -12.66016483
   0.32032798]
[-16.42107964 -18.38803291 -22.11332321 ... -14.84155655 -11.4440918
  -7.33137131]
[ -0.23711906  -1.64622866  -5.06937038 ... -15.87333292  -9.45809366
   1.18123636]
[-15.79523087 -13.79847527 -14.81175423 ...   4.32133675   5.69224358
   6.07967377]
[-0.22808185 -1.52733359 -4.45592883 ... -6.43799311 -2.14628384
  2.52847813]
[13.47064972 16.27206802 11.08646393 ...  7.59959221  5.39422035
  8.76188278]
[0.19451509 1.36759809 4.15656321 ... 0.71987873 1.69674154 1.392411  ]
[-0.41723251  0.83446503  0.05960464 ... -0.11920929 -2.11596489
 -1.34110451]
[-0.0060248  -0.02303188 -0.0103838  ... -0.36134069 -0.33968261
 -0.32667715]
[-16.00384712 -15.76542854 -15.437603   ... -10.69903374 -13.7090683
 -11.77191734]
[-0.23109426 -1.57327698 -4.67105389 ...  2.68591141  1.28673423
  1.22298484]
[  7.06315041  10.99705696  11.1758709  ...  -6.16908073 -10.55002213
  -7.00354576]
[ 0.10199132  0.75267601 

[ 0.23023357  1.61517274  5.06553469 ... -2.33362353 -1.76348977
 -2.43564455]
[-47.56450653 -15.85483551 -35.1369381  ...  -6.02006912 -10.90764999
  -2.11596489]
[ -0.68682762  -4.22823164 -11.12092039 ...  -1.73355569   2.83383226
   3.06407841]
[-97.87082672 -43.80941391 -29.56390381 ... -15.7058239  -24.19948578
 -16.68930054]
[ -1.41324681  -8.86171805 -23.20631834 ...  -5.83161764  -2.41639616
  -1.3102072 ]
[-62.52527237 -42.91534424 -46.49162292 ...  -1.4603138  -25.06375313
  -8.67247581]
[ -0.90285987  -5.87690495 -16.47920451 ...  -4.41591859  -2.85406117
  -2.69354889]
[-17.94099808 -25.18296242 -38.08736801 ...  -2.56299973   0.8046627
  -6.34789467]
[-0.25906656 -1.87214372 -6.16791703 ... -6.69332368 -2.33373698
  0.15047986]
[-16.06345177  -9.26852226 -43.18356514 ...  -0.56624413   2.5331974
  -3.27825546]
[-0.23195494 -1.48447382 -4.53706416 ... -6.10755358 -3.18958928
 -2.14905467]
[-18.89467239 -18.41783524 -36.68665886 ...  -3.15904617  -8.04662704
  -1.69873238]


[0.2005399  1.35921492 3.98617385 ... 1.06862436 1.39379388 1.83366838]
[-5.96046448 -6.13927841 -4.29153442 ...  1.16229057  0.74505806
  2.38418579]
[-0.08606862 -0.58981473 -1.74113197 ... -0.4590852  -1.10146998
 -0.7301268 ]
[  1.43051147   1.1920929    4.38094139 ... -10.60962677 -12.75539398
 -11.92092896]
[ 0.02065647  0.1374931   0.44260451 ... -0.58841205 -0.63569132
 -0.19091661]
[-6.97374344 -1.28149986  2.32458115 ... -3.42726707 -6.28829002
 -5.9902668 ]
[-0.10070029 -0.60486669 -1.43485091 ... -0.29501671  1.22343211
  2.33031866]
[12.12954521 16.54028893 21.99411392 ... -4.08291817 -5.48362732
 -7.59959221]
[ 0.17514965  1.25870927  4.07495437 ... -3.42786774 -1.52049453
  1.16738198]
[  4.08291817   7.77840614  12.75539398 ... -23.03719521 -12.39776611
 -10.75863838]
[ 0.05895701  0.45561693  1.634836   ... -4.48488025 -3.956399
  0.20626763]
[ 34.09385681  32.39512444  33.9448452  ...  -4.67896461 -12.33816147
 -11.20567322]
[0.49231253 3.33444132 9.86613917 ... 3.280

[0.26035759 1.80349045 5.34376391 ... 5.68270281 6.37211118 5.44633773]
[17.61317253 20.95103264 11.14606857 ... 20.02716064 19.967556
 19.04368401]
[0.25433279 1.78347097 5.35909737 ... 5.31524159 6.23093062 5.42842437]
[18.32842827 20.86162567 11.29508018 ... 21.48747444 21.51727676
 20.5039978 ]
[0.26466102 1.84231963 5.49328726 ... 5.82002362 6.51533712 5.61351035]
[-0.92387199 -0.86426735 -6.49690628 ... 25.18296242 26.64327621
 25.1531601 ]
[-0.01334064 -0.09016038 -0.34674294 ...  2.62249351  5.1225708
  6.2479168 ]
[16.71910286 16.12305641 12.2487545  ... 48.60758781 48.24995995
 47.83272743]
[0.24142249 1.63858078 4.79463265 ... 0.00823534 4.06134924 6.94324617]
[23.4246254  23.30541611 18.7754631  ... 21.51727676 21.72589302
 21.30866051]
[0.33824969 2.30610303 6.80111452 ... 0.56170991 4.519283   7.36899488]
[24.46770668 24.70612526 23.00739288 ... 19.58012581 20.08676529
 21.18945122]
[0.3533117  2.41403286 7.18351542 ... 1.21139874 6.38394901 9.49727334]
[26.94129944 36.98

[-0.15148078 -0.91432446 -2.21882975 ... -0.17581726  2.88323801
  1.99875911]
[-3.51667404  6.49690628  9.59634781 ... 30.36856651 18.29862595
 19.93775368]
[-5.07804884e-02 -2.01871987e-01 -1.30922358e-03 ... -2.95272145e-01
  3.62755656e+00  2.84364188e+00]
[-22.02391624 -13.88788223 -20.2357769  ...  -0.20861626  20.26557922
  13.56005669]
[-0.31802357 -2.05234105 -5.75706569 ... -2.90166262 -6.04939008
 -7.41018788]
[-19.63973045 -17.49396324 -25.39157867 ... -10.93745232  -8.37445259
 -11.29508018]
[-0.28359612 -1.90394695 -5.66953386 ... -2.12553528 -2.51233694
 -2.37847761]
[-22.53055573 -12.96401024 -28.93805504 ...   8.28504562  -3.87430191
  -9.983778  ]
[-0.3253394  -2.08159936 -5.90389736 ... -4.25303019 -2.37996951
  2.31597376]
[-39.45827484 -38.59400749 -40.32254219 ...   8.55326653  17.25554466
  15.73562622]
[ -0.56977429  -3.87500034 -11.52611044 ...  -6.96355572  -9.81600538
  -7.93445617]
[-41.21661186 -43.15376282 -42.49811172 ...  -5.87105751   1.69873238
  -2.20

[-0.29650641 -1.9825643  -5.75170541 ...  0.01824471 -0.04572559
 -0.12088514]
[-2.77161598 -0.44703484  2.11596489 ...  1.75833702 -2.32458115
 -1.69873238]
[-0.04002191 -0.23949643 -0.54781101 ...  0.62978872  0.85321639
  0.05471654]
[-13.91768456 -10.43081284  -8.43405724 ...  -0.23841858  -4.73856926
  -4.2617321 ]
[-0.20097024 -1.32083814 -3.71434418 ...  0.78034082  1.15986754
 -0.40948299]
[-18.11981201 -11.02685928 -15.79523087 ...   0.08940697  -5.06639481
  -5.24520874]
[-0.26164862 -1.68276566 -4.69064467 ... -0.28286265  0.43284214
  0.77705486]
[-21.36826515  -3.7252903  -12.33816147 ...  -0.17881393   1.04308128
  -5.54323196]
[-0.30855602 -1.850466   -4.66061407 ... -1.59389753  0.34611447
  1.53981665]
[-19.75893974 -10.07318497 -15.13957977 ...  -2.20537186  -4.44054604
  -6.13927841]
[-0.28531749 -1.80681479 -4.92080586 ...  0.37777646  0.8753993
  0.22384151]
[-5.78165054 -2.23517418 -6.5267086  ...  1.84774399 -2.05636024
 -3.66568565]
[-0.08348657 -0.51840486 -1.4

 -12.72559166]
[-0.1656821  -1.17733029 -3.75027834 ... -2.57721697 -4.62878141
 -5.0724026 ]
[  0.86426735  -5.39422035 -11.77191734 ...  -7.00354576 -13.41104507
 -11.74211502]
[ 0.01247995 -0.00522332 -0.45490928 ... -0.83005784 -3.4709643
 -4.62421475]
[  3.63588333  -3.87430191 -16.68930054 ...  -6.46710396 -12.90440559
 -11.68251038]
[ 0.05250186  0.24976546  0.14265901 ... -1.82854945 -4.42200253
 -5.76596576]
[12.48717308  3.57627869  0.41723251 ... -8.04662704 -8.28504562
 -7.03334808]
[  0.18031377   1.10157985   2.74313196 ...  -7.33755344 -11.94948283
  -9.9336694 ]
[-16.89791679 -24.13988113 -25.45118332 ...  -6.70552254  -8.40425491
  -6.67572021]
[-0.24400455 -1.769378   -5.69422921 ... -4.71392936 -7.82783349
 -7.09319427]
[-22.41134644 -29.77252007 -33.4084034  ... -15.94424248 -17.91119576
 -18.03040504]
[-0.32361803 -2.3142896  -7.35847217 ... -3.36759636 -6.8145085
 -6.53923576]
[-11.11626625 -18.68605614 -30.99441528 ...  -8.49366188 -13.32163811
 -10.5202198 ]
[-0

[ 0.01420132  0.04654325  0.08339141 ... -0.38614384  2.0668693
  5.1289579 ]
[ 6.73532486  4.11272049  9.86456871 ...  9.38773155 12.30835915
  6.19888306]
[ 0.09725755  0.62570272  1.80239563 ... -0.1255216  -0.1236336
  0.62016215]
[ 5.15580177  3.01003456  7.42077827 ... -2.29477882 -0.14901161
 -5.33461571]
[ 0.07444936  0.47697156  1.36620679 ... -0.65239921 -0.30966291
  0.66806794]
[  3.51667404  -0.11920929   4.50015068 ...  -9.95397568  -7.83801079
 -11.7123127 ]
[ 0.05078049  0.29396542  0.74110705 ... -1.04356256 -0.76188615
  0.3690701 ]
[  4.50015068   0.92387199   6.13927841 ... -13.58985901 -10.72883606
 -15.88463783]
[ 0.06498181  0.39171949  1.04436862 ... -1.49243655 -0.53579078
  0.70001529]
[  8.28504562   5.12599945  10.04338264 ... -13.47064972 -12.75539398
 -16.80850983]
[ 0.11963539  0.77063704  2.19254611 ... -3.8191584  -2.85673899
 -1.32416101]
[  5.87105751   3.66568565   9.74535942 ... -12.48717308 -16.00384712
 -19.37150955]
[ 0.0847776   0.54657879  1.59

[0.26380033 1.89024019 5.94780944 ... 1.71308762 2.10347914 2.82725012]
[25.9578228  29.53410149 26.67307854 ...  8.94069672  3.84449959
 12.30835915]
[0.37482886 2.60903946 7.9331314  ... 0.40180382 0.33772083 0.32899975]
[23.06699753 25.89821815 20.89142799 ...  9.38773155  5.33461571
  9.62615013]
[ 0.33308558  2.31347304  6.97989742 ... -0.7364822  -0.42619038
 -0.35418002]
[15.73562622 19.93775368 13.14282417 ...  3.78489494  0.35762787
  3.9935112 ]
[ 0.22722117  1.61097263  4.93639894 ... -2.03017059 -2.11045693
 -1.82198996]
[27.9545784  32.72294998 24.70612526 ... 10.2519989  10.10298729
 11.80171967]
[ 0.40366185  2.82297613  8.56244432 ... -2.55797395 -3.11642072
 -2.03037787]
[14.96076584 19.1628933  13.73887062 ... 14.30511475  4.41074371
 15.10977745]
[ 0.21603225  1.53463239  4.72866921 ... -2.31526    -1.83961707
 -1.48264257]
[ 9.50694084  9.95397568  9.80496407 ... 22.05371857  2.71201134
 28.90825272]
[ 0.13727946  0.94309126  2.83345378 ... -0.4616204   0.13598679
 

[-0.43292518 -2.93097215 -8.77783418 ...  6.2336612   2.87506176
  1.26455091]
[ -9.14931297 -12.57658005 -22.17292786 ...   2.59280205 -10.2519989
   0.74505806]
[-0.13211534 -0.95089161 -3.16278054 ...  8.71628347  3.66021059
  3.87625171]
[14.7819519  11.95073128 -9.26852226 ... 14.2455101   0.56624413
  7.15255737]
[ 0.21345019  1.41545443  3.75514692 ...  7.07508011 -1.99233757
 -3.46376145]
[ 0.83446503 -3.12924385 -3.24845314 ... 39.24965858 29.02746201
 40.02451897]
[ 0.01204961  0.02497694 -0.14720362 ...  9.70333204  2.30677522
  0.27682114]
[-21.84510231 -45.03130913 -11.9805336  ... -23.48423004 -40.14372826
 -30.87520599]
[ -0.31544151  -2.48701469  -8.22155389 ...   8.98508034  -2.39720733
 -17.415449  ]
[-15.7058239  -18.32842827 -27.86517143 ...  -7.30156898 -16.71910286
 -21.10004425]
[ -0.22679083  -1.58522828  -5.00785934 ...   2.64141761  -7.57616475
 -14.54021655]
[-29.38508987 -30.66658974 -35.82239151 ...  -3.24845314  -9.26852226
 -10.63942909]
[-0.42431832 -2.9

[-0.41442043 -2.80772953 -8.2641592  ...  3.18842197  4.14575743
  5.37082784]
[-26.37505531 -25.45118332 -26.55386925 ...  -3.60608101  -2.86102295
   0.02980232]
[-0.38085366 -2.58516394 -7.66952011 ...  2.70194595  3.41594303
  4.92428227]
[-36.09061241 -35.49456596 -33.08057785 ...   5.60283661   9.62615013
  12.18914986]
[ -0.52114552  -3.54708697 -10.50385733 ...   7.11293407   6.81493291
   7.12330781]
[-53.13754082 -34.68990326 -40.79937935 ...   2.23517418   7.48038292
  18.32842827]
[ -0.76730179  -4.96879688 -13.87373493 ...  -2.16549212   0.24385222
   6.36657029]
[-20.71261406 -26.34525299 -29.65331078 ...  19.19269562  15.40780067
  16.27206802]
[-0.29908847 -2.12196838 -6.68463499 ...  9.73969336  6.81390306
  5.02493083]
[-24.46770668 -28.96785736 -32.7527523  ...   5.12599945   4.20212746
   4.7981739 ]
[-0.3533117  -2.47557193 -7.68256992 ...  7.48213759  4.76514743
  2.73650322]
[-27.53734589 -30.4877758  -33.6766243  ...   0.38743019   0.11920929
   2.71201134]
[-0.

[ 0.23324597  1.59226123  4.77945857 ... -2.24158507  0.11017128
  3.19379536]
[ 24.28889275  24.79553223  31.26263618 ... -22.61996269 -20.65300941
 -24.19948578]
[ 0.35072964  2.40028897  7.27534902 ... -1.80354764  0.71305614
  3.8204352 ]
[ 24.58691597  23.90146255  32.7527523  ...  -9.53674316  -7.06315041
 -12.57658005]
[ 0.35503308  2.41243688  7.27983975 ... -4.49920533 -1.29651067
  2.17989876]
[ 25.24256706  24.67632294  31.6798687  ...  -9.7155571   -7.15255737
 -13.94748688]
[ 0.36450062  2.47875385  7.45742472 ... -4.73829818 -1.40379839
  2.10045496]
[ 17.01712608  16.27206802  18.89467239 ... -14.33491707  -4.55975533
 -13.14282417]
[ 0.24572592  1.6657907   4.96127645 ... -6.22863099  0.01590913
  5.77442937]
[ 17.31514931  16.89791679  19.78874207 ... -14.18590546  -4.73856926
 -14.27531242]
[ 0.25002935  1.69988611  5.08495715 ... -6.09636234  0.36954152
  6.10868466]
[ 22.05371857  23.90146255  30.27915955 ... -17.91119576 -14.27531242
 -18.89467239]
[ 0.31845391  2.

[ -0.96612031  -6.60588806 -19.7320879  ... -10.96292925 -10.0923563
  -6.67919547]
[-47.3856926  -47.26648331 -44.79289055 ... -13.38124275 -14.513731
 -13.53025436]
[ -0.68424556  -4.66677837 -13.86659718 ...  -9.56743772  -7.90131486
  -5.19956318]
[-47.62411118 -46.61083221 -45.62735558 ... -13.32163811 -15.02037048
 -13.14282417]
[ -0.68768831  -4.67735738 -13.87003729 ...  -8.98147421  -7.3867774
  -4.91602035]
[-33.88524055 -31.35204315 -37.34230995 ... -54.65745926 -85.8604908
 -78.55892181]
[-0.48930013 -3.30183857 -9.78679085 ... -6.48624872 -6.93891994
 -6.50061842]
[-22.14312553 -21.30866051 -25.30217171 ... -48.39897156 -81.24113083
 -71.37656212]
[-0.31974494 -2.16951977 -6.47743253 ... -6.70029272 -6.57813872
 -6.13658302]
[-23.72264862 -21.51727676 -21.90470695 ... -44.13723946 -78.29070091
 -67.41285324]
[-0.34255313 -2.30534064 -6.75409951 ... -5.46973535 -5.78384664
 -6.24889519]
[-23.66304398 -19.72913742 -23.84185791 ... -39.36886787 -67.11483002
 -58.50195885]
[-0

[ 0.15922696  1.14748917  3.63457216 ... -0.3700499   0.43341054
  1.81860151]
[ 5.42402267  8.55326653  6.58631325 ... 15.437603   14.21570778
 11.59310341]
[0.07832245 0.57956776 1.87257311 ... 0.32667575 0.74773821 1.46147106]
[2.5331974  8.7916851  4.38094139 ... 6.67572021 9.53674316 5.87105751]
[ 0.03657917  0.33994594  1.29673694 ... -0.88290478  0.84318464
  3.11970926]
[12.75539398 16.71910286 10.28180122 ...  7.30156898 10.87784767
  6.73532486]
[ 0.18418686  1.31391355  4.04297562 ... -0.20612142  1.4544313
  4.50390374]
[ 5.30481339 11.38448715  3.21865082 ... -2.23517418  3.84449959
  0.38743019]
[ 0.07660108  0.61042707  2.03873799 ... -2.10284252 -1.24652748
  2.93885633]
[ 2.56299973  7.89761543  5.51342964 ... 11.4440918   7.15255737
 10.13278961]
[ 0.03700951  0.32954147  1.24373019 ...  2.24770727 -0.28496436
 -2.74087725]
[ 8.16583633 12.93420792  9.68575478 ...  0.92387199  0.74505806
  3.54647636]
[ 0.11791402  0.87336366  2.82064762 ... -1.29789582 -2.19259791
 -

[-0.31587185 -2.17623072 -6.51803318 ...  0.00988511  1.38820583
  3.30089485]
[-25.00414848 -22.26233482 -18.47743988 ... -14.7819519  -13.56005669
 -16.18266106]
[-0.36105788 -2.42384949 -7.01729273 ... -4.17446882 -0.21958476
  4.47723922]
[-36.38863564 -28.40161324 -28.25260162 ... -29.44469452 -23.33521843
 -26.40485764]
[-0.52544895 -3.4697235  -9.89590471 ... -0.50145647  1.43154998
  2.90760407]
[  0.74505806  -0.77486038  -3.09944153 ... -12.06994057  -8.31484795
 -16.03364944]
[ 0.01075858  0.05145658  0.03546344 ... -3.49449195 -1.61851534
  2.39755249]
[ -6.49690628  -6.02006912  -4.02331352 ... -11.62290573  -7.92741776
 -14.60313797]
[-0.0938148  -0.63319812 -1.83190233 ... -1.40944613 -1.2563975
 -0.35470976]
[ 1.25169754 -0.41723251  2.77161598 ... -0.5364418   1.96695328
 -2.32458115]
[ 0.01807441  0.09921965  0.24916278 ... -2.30061475 -1.83602637
 -0.66863792]
[-0.2682209  -4.7981739  -1.37090683 ... -1.75833702  0.5364418
 -1.4603138 ]
[-0.00387309 -0.09183762 -0.47

[-0.06799421 -0.5585893  -1.95502232 ... -1.0365083   1.1235254
  3.61928986]
[ -7.53998756 -19.13309097 -17.94099808 ...  -6.40749931  -8.40425491
  -5.57303429]
[-0.10887681 -0.9102528  -3.3389521  ... -0.90567899  0.75837167
  3.73250821]
[-27.56714821 -32.36532211  -2.35438347 ...  -3.39746475  -9.4473362
  -3.39746475]
[-0.39806739 -2.78523635 -8.13402451 ... -2.23959123 -1.40490504
 -0.11050849]
[-27.89497375 -33.37860107  -2.11596489 ...  -3.12924385  -9.38773155
  -3.15904617]
[-0.40280116 -2.82743204 -8.27974265 ... -2.41771    -1.45285441
  0.18303017]
[-32.06729889 -35.1369381   -9.53674316 ...  -3.9935112   -9.62615013
  -3.69548798]
[-0.4630492  -3.20363712 -9.34881599 ... -1.77102361 -0.70029257
  0.49529029]
[-9.50694084 -2.38418579 -6.07967377 ... -3.51667404 -8.37445259
 -5.7220459 ]
[-0.13727946 -0.83378411 -2.14318255 ... -2.3617216  -0.44792504
  2.05474681]
[-18.89467239   4.38094139  -7.77840614 ...   1.78813934  -5.66244125
 -12.2487545 ]
[-0.27283754 -1.52542959

[  0.14889872   1.07616056   3.58306736 ... -22.49384412 -18.83619756
 -15.94098672]
[ 22.44114876  24.28889275  18.65625381 ... -77.78406143 -65.44589996
 -60.05167961]
[  0.32404837   2.23761228   6.69019622 ... -25.71223613 -18.91991002
 -12.21147171]
[ 14.2455101   12.18914986  23.4246254  ... -46.40221596 -42.08087921
 -51.20038986]
[  0.20570401   1.37379241   4.14261316 ... -11.38270088 -10.48453427
 -12.85781401]
[-24.28889275 -13.85807991 -14.33491707 ... -25.92802048 -10.75863838
 -11.95073128]
[ -0.35072964  -2.24235304  -6.1112781  ... -16.09851762  -6.6164903
  -0.74457125]
[-13.9772892   -9.1791153  -22.35174179 ... -31.73947334 -21.12984657
 -10.49041748]
[ -0.20183092  -1.30777537  -3.8216996  ... -13.24164082  -8.99422278
  -5.96444249]
[  0.5364418    5.12599945  -8.55326653 ... -15.52700996 -15.25878906
  -7.30156898]
[ 7.74617620e-03  1.19123781e-01  4.12159328e-01 ... -8.32263775e+00
 -5.94029790e+00 -5.30100809e+00]
[20.74241638 26.40485764 20.14636993 ... -4.9769

[-0.01118892 -0.34960813 -1.95686151 ... 10.83178436  9.23483432
  9.94917834]
[-45.12071609  -2.2649765    1.1920929  ... -13.76867294 -38.4747982
   1.90734863]
[-0.65153949 -3.82651792 -8.97686302 ...  2.4435391   2.35805496
  4.05669109]
[ -0.2682209  -41.69344902  42.28949547 ... -32.06729889  47.32608795
  29.62350845]
[-3.87308810e-03 -6.24602410e-01 -2.94731898e+00 ... -3.08280576e+00
 -5.41170586e+00  2.03812484e+01]
[   6.64591789   29.65331078  -17.49396324 ...    9.1791153  -104.66575623
   50.96197128]
[  0.09596652   0.98698932   3.53738413 ... -12.05553955   2.53421839
  24.80039074]
[ -2.17556953  10.28180122 -43.24316978 ...  81.74777031 -19.99735832
  47.35589027]
[-0.03141505 -0.0344565  -0.1844016  ...  8.03792741 18.53289207
 16.44038959]
[ -8.64267349  -6.73532486 -19.66953278 ...   9.59634781 -21.24905586
   4.2617321 ]
[-0.12479951 -0.82394541 -2.53663905 ... 12.0835477   9.86121825
  2.16010412]
[ 18.38803291  18.06020737  20.59340477 ...   6.04987144 -11.50369

[-0.39290327 -2.61444431 -7.62655782 ...  6.44646619  4.37661176
  2.12907064]
[-13.35144043  -7.80820847 -12.30835915 ...  -9.03010368  24.55711365
   7.00354576]
[-0.19279372 -1.23535736 -3.43929506 ... 10.46370985 10.99877319
  6.61399349]
[-5.75184822  1.31130219 -6.49690628 ... 39.33906555 28.04398537
 14.99056816]
[-0.08305622 -0.46468821 -1.10581858 ...  8.76134793  9.34382633
  9.40255975]
[-32.96136856 -31.91828728 -39.96491432 ...  51.67722702 126.51085854
  56.65421486]
[-0.47595949 -3.23233467 -9.69201228 ... 62.43904909 27.86325347
 -2.40805622]
[-22.85838127 -19.07348633 -19.66953278 ...   2.32458115  77.30722427
   0.11920929]
[-0.33007317 -2.19738372 -6.3477168  ... 27.26346435 13.2906649
 -8.03366917]
[-26.10683441 -25.03395081 -23.33521843 ...  10.63942909 -72.98588753
 -65.8929348 ]
[ -0.37698058  -2.55658675  -7.53562821 ... -43.08460891 -14.03051424
  17.11795922]
[-16.36147499 -16.65949821 -14.96076584 ...   3.27825546 -25.51078796
  -8.58306885]
[ -0.23625837  -1

[ 0.48628773  3.38801052 10.3409526  ... -2.89626698 -4.40887121
 -5.95752841]
[26.79228783 29.17647362 24.91474152 ... -6.28829002 -4.85777855
 -6.49690628]
[0.38687847 2.67403831 8.04048622 ... 3.95753389 4.12591135 1.47542263]
[ 33.43820572  28.25260162  25.62999725 ... -12.60638237 -10.72883606
 -11.14606857]
[ 0.48284498  3.21949559  9.26983843 ...  2.12693415  0.65354738
 -0.74064029]
[ 4.20212746  3.60608101  2.32458115 ... 11.29508018 13.76867294
 11.41428947]
[ 0.06067838  0.40539217  1.15666035 ... -0.02813525 -0.94504475
 -1.36737585]
[12.2487545  14.63294029 12.21895218 ... 16.06345177 20.2357769
 17.40455627]
[ 0.17687102  1.24119059  3.7966886  ... -0.54538495 -0.33564652
 -0.54941827]
[ 3.60608101  8.97049904  8.04662704 ... 11.89112663 15.94424248
 13.05341721]
[ 0.05207152  0.43273753  1.57403751 ... -0.5859699  -1.06843541
 -1.66873611]
[15.94424248 21.72589302 21.30866051 ... 23.66304398 27.80556679
 25.18296242]
[ 0.23023357  1.65433396  5.2453659  ... -2.34980439 -

[-0.19623646 -0.71015919  1.25766131 ... 70.74550684 71.34789832
 35.87124305]
[ 16.09325409  15.05017281  13.14282417 ... -56.89263344 -51.79643631
 -42.55771637]
[ 0.23238529  1.5704662   4.59522224 ... -2.96464941 -1.1095117
  2.6127868 ]
[ -4.7981739   -4.02331352  -3.69548798 ... -56.95223808 -47.56450653
 -41.60404205]
[-0.06928524 -0.46153338 -1.32783397 ... -3.08553168 -1.32893768
  2.5847316 ]
[ 15.76542854  17.28534698  24.46770668 ... -34.33227539 -24.43790436
 -17.73238182]
[ 0.22765151  1.57517792  4.88272615 ... -4.26137129 -0.86965392
  4.02607206]
[  2.41398811   3.24845314  10.7884407  ... -30.07054329 -28.87845039
 -26.7624855 ]
[ 0.03485779  0.24987884  0.89991887 ... -3.08304522 -0.11579572
  4.10852802]
[-21.1596489  -15.64621925 -11.86132431 ...  -6.64591789  -5.81145287
  -6.88433647]
[-0.30554362 -2.00506251 -5.61535295 ... -0.5625915   2.15841892
  2.52352616]
[-27.4181366  -30.07054329 -27.86517143 ... -29.35528755 -28.13339233
 -35.91179848]
[-0.39591567 -2.7

[ 0.09166309  0.5935574   1.62516578 ... -3.18348289 -4.77237793
 -5.44632265]
[  9.86456871   7.92741776   4.41074371 ... -18.62645149 -17.1661377
 -12.45737076]
[ 0.14244357  0.94389777  2.65494371 ... -5.58770006 -6.85728939
 -6.8339261 ]
[-12.27855682 -14.12630081 -13.73887062 ...  -8.76188278  -8.73208046
  -5.60283661]
[-0.17730137 -1.23638058 -3.78185198 ... -6.89751896 -9.5064417
 -9.72783875]
[-17.10653305 -27.65655518 -23.93126488 ...  -7.89761543 -13.4408474
  -0.62584877]
[ -0.24701695  -1.83769923  -6.00867222 ...  -5.15664183  -9.60149251
 -10.95290773]
[-37.9383564   -9.95397568 -27.98438072 ...  -9.38773155 -37.4019146
 -11.77191734]
[-0.54782679 -3.33364376 -8.64329943 ...  3.64497199  4.75013861
  1.7293182 ]
[-15.19918442 -13.32163811 -11.26527786 ...  -5.60283661 -10.75863838
  -8.28504562]
[-0.21947499 -1.4703317  -4.24832851 ...  2.26151481  3.52857087
  3.19556174]
[-2.59280205  2.08616257  2.95042992 ... 26.91149712 27.62675285
 27.89497375]
[-0.03743985 -0.1878

[-0.22076602 -1.71841096 -5.45996178 ...  5.26291553  1.33369948
 -1.79739459]
[  0.17881393  -8.85128975   0.59604645 ... -24.40810204 -10.01358032
 -33.9448452 ]
[ 0.00258206 -0.11277699 -0.70073284 ...  0.29418606  1.17985384
 -0.99141168]
[  0.56624413  -9.95397568   3.96370888 ... -24.7657299  -18.09000969
 -17.04692841]
[ 8.17651933e-03 -9.61240184e-02 -6.69226782e-01 ...  4.17105272e+00
 -2.51992456e+00 -8.68409966e+00]
[-0.56624413  1.81794167  1.37090683 ... -7.95722008 -3.12924385
 -5.75184822]
[-0.00817652 -0.02135965  0.06216928 ... -0.83763621 -5.08616854
 -7.51596645]
[ -6.55651093  -7.92741776  -4.41074371 ... -18.68605614 -16.18266106
 -17.85159111]
[-0.09467549 -0.66575172 -2.00949892 ... -2.64440917 -8.16220071
 -9.44184267]
[-47.53470421  81.03251457  71.22755051 ... -33.88524055 -55.43231964
   4.23192978]
[ -0.68639728  -2.82668033  -1.43278938 ... -23.61131904   0.8205448
  14.89831029]
[-37.43171692 -10.13278961 -24.37829971 ...   4.70876694   0.29802322
  -4.976

[-0.2724072  -1.8525666  -5.57228391 ...  0.63052873  0.66565908
 -1.93255394]
[-33.52761269 -27.06050873 -45.00150681 ...  -4.02331352 -20.62320709
 -12.81499863]
[-0.48413601 -3.20979932 -9.46677311 ...  3.93168965  0.70601243
 -5.31250077]
[-25.1531601  -31.59046173 -23.48423004 ...   5.453825     9.83476639
   6.64591789]
[-0.3632096  -2.57107599 -7.9029862  ... -2.86211675 -6.40202677
 -5.80349317]
[-13.58985901 -18.98407936 -14.72234726 ...   9.983778     9.53674316
  11.1758709 ]
[-0.19623646 -1.4167826  -4.46035399 ... -2.62741806 -5.85463936
 -4.48242379]
[-48.63739014 -53.67398262 -44.40546036 ... -18.41783524 -17.7025795
 -21.12984657]
[ -0.70231998  -4.86454659 -14.64397643 ...   1.54501644  -0.42734777
  -0.29602966]
[-22.11332321 -24.40810204 -18.26882362 ...   6.07967377   7.21216202
   8.16583633]
[-0.3193146  -2.21176963 -6.63066204 ... -0.02708094 -1.05604946
 -0.37787936]
[ 0.35762787 -0.32782555 -0.38743019 ...  1.10268593  0.89406967
  1.25169754]
[ 0.00516412  0.0

[  0.56504052   3.71919406  10.28162715 ... -10.74369515 -19.59583952
 -16.28407721]
[ -7.12275505 -20.17617226  -8.28504562 ...   0.47683716  25.21276474
 -11.56330109]
[ -0.10285201  -0.89023333  -3.20581718 ... -18.5499835  -17.98003347
  -8.68232221]
[ 0.02980232 15.1693821  -1.66893005 ... 12.96401024 11.89112663
 -3.01003456]
[ 4.30343122e-04  2.21550470e-01  1.25717810e+00 ... -1.23645179e+01
 -9.72117291e+00 -4.11799758e+00]
[31.20303154 23.45442772 19.01388168 ...  5.57303429  2.38418579
  1.63912773]
[ 0.45056925  2.96227382  8.33475385 ... -5.22608545 -6.0131687
 -7.25586083]
[17.13633537 -1.90734863 18.89467239 ... -1.96695328  1.1920929
 -3.30805779]
[  0.2474473    1.41330468   3.45598538 ...  -4.3034588   -9.62594096
 -13.8112827 ]
[80.34706116 70.4228878  97.42379189 ... 27.4181366  18.56684685
 19.81854439]
[ 1.16020506  7.77259216 23.00479414 ... -0.43788241 -2.17124351
 -4.52280527]
[42.61732101 32.30571747 40.88878632 ... 17.55356789 10.96725464
  9.23871994]
[ 0.61

[-0.1437346  -1.03963557 -3.26225205 ... -2.32338241  3.97475207
  9.85526163]
[-0.29802322 -1.57952309  1.28149986 ... -7.83801079 -5.30481339
  4.88758087]
[-4.30343122e-03 -4.78663879e-02 -1.72451898e-01 ... -6.27081691e+00
 -2.02834543e+00  3.59103527e+00]
[-1.37090683 -4.32133675 -1.22189522 ... -2.98023224 -0.38743019
  2.92062759]
[-0.01979578 -0.17766748 -0.64846963 ... -3.2978118  -2.75820531
 -1.15022298]
[-1.25169754 -3.51667404 -1.66893005 ...  9.14931297  9.65595245
  7.89761543]
[-0.01807441 -0.15602494 -0.56400836 ...  0.83512254  0.34281479
  0.50822267]
[5.69224358 3.1888485  3.57627869 ... 1.81794167 5.81145287 5.1856041 ]
[0.08219554 0.52465838 1.43039417 ... 0.60634407 0.90699077 1.48533957]
[  2.89082527   2.62260437   1.40070915 ... -21.63648605 -14.99056816
 -11.7123127 ]
[ 0.04174328  0.28093476  0.80477565 ... -1.19777989  1.69875974
  5.25041541]
[  7.92741776   5.9902668    6.43730164 ... -17.79198647  -9.59634781
  -4.67896461]
[ 0.11447127  0.75304715  2.14

[ 0.66444978  4.47878265 13.20145252 ...  0.57403748  3.04264325
  6.40354647]
[30.30896187 27.38833427 33.52761269 ... 13.41104507 15.437603
 22.29213715]
[ 0.43765896  2.94390451  8.70065469 ... -0.19580358  0.31673474
  2.5460789 ]
[-1.16229057 -5.84125519  0.50663948 ...  9.7155571  11.53349876
 13.82827759]
[-0.01678338 -0.18207424 -0.71060283 ... -0.32976626 -1.4595245
 -1.02568881]
[15.76542854 12.66598701 18.2390213  ... -2.05636024  0.89406967
  1.51991844]
[ 0.22765151  1.50847473  4.4043823  ... -0.02348427 -2.5171562
 -3.83708821]
[14.69254494 12.45737076 17.85159111 ... -2.68220901  0.77486038
  0.89406967]
[ 0.21215916  1.4152528   4.17191365 ... -0.17705597 -2.51174028
 -3.80362997]
[14.93096352 12.45737076 17.58337021 ... -2.29477882  0.23841858
  0.65565109]
[ 0.2156019   1.43529936  4.2145591  ... -0.1513647  -2.22853788
 -3.2272938 ]
[39.69669342 38.89203072 42.79613495 ... 10.2519989  15.85483551
 14.21570778]
[ 0.57321704  3.89935033 11.63340567 ... -2.92463005 -4.

[ 0.21818396  1.52607467  4.75846659 ... -2.15971631 -2.79403741
 -2.5707779 ]
[14.69254494 16.89791679 21.90470695 ... 16.42107964  8.88109207
  8.70227814]
[ 0.21215916  1.47937393  4.60380753 ... -2.16591217 -2.62872201
 -2.11119548]
[23.1564045  25.51078796 29.56390381 ... 15.73562622  7.65919685
  4.97698784]
[ 0.33437661  2.31539604  7.08999606 ... -3.80220012 -4.10393237
 -3.11113943]
[12.69578934 14.57333565 18.53704453 ... 12.69578934  5.69224358
  6.04987144]
[ 0.18332617  1.27791721  3.97013197 ... -3.64005751 -4.34132856
 -1.80882341]
[15.73562622 16.39127731 20.56360245 ... 15.02037048  8.46385956
  7.51018524]
[ 0.22722117  1.5597618   4.74536177 ... -6.08694728 -3.27571262
  0.70847132]
[43.77961159 26.7624855  42.61732101 ...  6.46710396 -8.34465027
 -7.56978989]
[ 0.63217405  4.06749805 11.40758484 ... -1.34220011  0.44508195
  1.99128954]
[ 37.78934479  39.96491432  51.97525024 ...  -8.34465027 -18.92447472
 -12.63618469]
[ 0.54567508  3.75447019 11.48401253 ...  0.08

[ -0.12695122  -1.02668618  -3.65478093 ... -14.33132706  -8.7846895
  -3.58730101]
[ -6.43730164 -15.437603   -14.36471939 ...  35.49456596  35.25614738
  37.22310066]
[ -0.09295411  -0.76417491  -2.76144095 ... -18.93133873 -14.36250337
  -9.69436859]
[-16.83831215 -25.36177635 -22.59016037 ...  35.70318222  36.98468208
  38.23637962]
[ -0.24314386  -1.78201043  -5.74402526 ... -14.17113866  -9.65073335
  -5.93883262]
[-15.91444016 -26.70288086 -20.74241638 ...  32.15670586  26.07703209
  30.54738045]
[ -0.22980323  -1.72369544  -5.64984654 ... -12.42857605  -7.04951725
  -4.79749951]
[ -7.09295273 -16.06345177  -6.73532486 ...  36.03100777  29.02746201
  38.11717033]
[ -0.10242166  -0.82834016  -2.83182133 ... -11.63419769  -2.45985948
   2.52499234]
[ -0.47683716  -1.60932541  -8.55326653 ... -15.19918442 -20.71261406
 -18.80526543]
[-6.88548996e-03 -6.33316524e-02 -3.51859856e-01 ...  1.39861647e+01
  1.40554565e+01  1.44767796e+01]
[-43.72000694 -44.43526268 -36.83567047 ... -25.

[ -0.83099257  -5.7071713  -17.10453204 ...  -0.10894793   3.49674823
   2.78853456]
[-38.35558891 -33.49781036 -30.13014793 ...  26.43465996  19.34170723
  18.29862595]
[ -0.5538516   -3.70869631 -10.73528957 ...  -6.8916128   -6.01418319
  -4.59287256]
[-72.95608521 -33.08057785 -70.1546669  ...  25.57039261  -9.29832458
   1.63912773]
[ -1.05347996  -6.6119288  -18.02916257 ...  -5.57166607 -11.99933396
  -9.57024783]
[ -82.82065392 -109.70234871  -31.79907799 ...   21.81529999  -34.45148468
  -72.71766663]
[ -1.19592354  -8.54776747 -25.84247954 ...  24.96236642   6.48374884
  -8.23250485]
[-62.13784218 -56.26678467 -56.53500557 ...  33.34879875  55.46212196
   3.78489494]
[ -0.89726541  -6.03712301 -17.67124498 ... -10.24748508 -54.74113761
 -58.01466434]
[-48.84600639 -46.01478577   7.36117363 ...  18.26882362   0.29802322
   7.53998756]
[ -0.70533238  -4.77148915 -13.29317835 ...   1.17007821  -4.06872807
 -12.7522189 ]
[-24.46770668 -18.68605614 -11.47389412 ...  11.32488251   

[ 0.07832245  0.52792658  1.49699498 ... -7.79206126 -9.42156162
 -8.72461342]
[6.67572021 3.87430191 0.32782555 ... 0.50663948 2.92062759 0.74505806]
[ 0.09639686  0.61724834  1.63300963 ... -5.71322011 -7.73332302
 -7.84133774]
[13.41104507 10.75863838  8.01682472 ... -7.56978989 -3.4570694
 -4.50015068]
[ 0.19365441  1.28297297  3.63703149 ... -4.10152494 -5.72084123
 -5.68987236]
[ 13.79847527  10.84804535   9.56654549 ... -11.62290573  -6.16908073
  -5.63263893]
[ 0.19924887  1.31683967  3.74251943 ... -2.6328405  -5.58066822
 -6.13671682]
[  1.54972076   0.38743019  -2.47359276 ... -10.87784767  -6.70552254
  -4.08291817]
[  0.02237784   0.13589711   0.29922772 ...  -6.26422334  -9.15300365
 -10.02136946]
[144.92869377 146.65722847 151.39579773 ...  18.32842827  15.49720764
   9.38773155]
[ 2.0927586  14.30352232 42.79474424 ... -6.24116958 -1.51390338
  1.46149398]
[144.45185661 146.74663544 153.7501812  ...  -5.06639481  -3.27825546
  -9.53674316]
[ 2.08587311e+00  1.42647202e+

[-0.12566019 -0.81862882 -2.31857381 ...  0.49098872  0.44829964
 -0.4406992 ]
[ 4.23192978 17.19594002 -5.27501106 ... 28.01418304 26.10683441
 21.87490463]
[ 0.06110872  0.60413446  2.1953917  ...  1.17483693  0.55830776
 -0.73510073]
[ 16.7787075   13.4408474  -27.56714821 ...  17.49396324  22.44114876
  15.88463783]
[ 0.24228318  1.60486154  4.00580006 ...  2.17647169 -1.48869439
 -4.95119948]
[  9.38773155 -30.84540367  -9.56654549 ...  33.85543823  44.94190216
  21.18945122]
[ 0.13555808  0.34392824 -0.89999643 ... -1.69012829  3.79634785
  7.41344385]
[-0.23841858 -5.60283661 -1.16229057 ... 36.2098217  12.84480095
 22.82857895]
[-3.44274498e-03 -1.00951069e-01 -5.34396130e-01 ...  3.64503984e+00
  3.99107487e+00  4.49477579e+00]
[ 5.12599945 -0.62584877  2.14576721 ... 28.13339233 17.01712608
 31.82888031]
[0.07401902 0.42196388 0.97851117 ... 2.66807048 1.06993107 0.47522269]
[ 1.63912773 -1.87754631 -0.38743019 ... 24.43790436 21.6960907
 33.91504288]
[0.02366887 0.1107085  0

[-0.35115999 -2.38859347 -7.08270947 ... -6.08922777 -9.63222564
 -9.60656149]
[29.92153168 27.65655518 25.48098564 ... -1.28149986 -7.51018524
 -9.35792923]
[0.43206449 2.91520194 8.53142179 ... 2.62119823 3.35945015 3.15979901]
[ 14.60313797  10.55002213  12.45737076 ...  -1.96695328  -7.53998756
 -12.06994057]
[0.21086813 1.38019338 3.91620459 ... 3.02971691 6.44344804 7.21272615]
[10.99705696  8.22544098 12.39776611 ... -5.9902668  -5.39422035
 -8.2552433 ]
[0.15879661 1.04342237 3.01629696 ... 7.01734976 7.5147625  4.53424624]
[14.7819519  13.02361488 13.08321953 ...  9.23871994  5.60283661
  2.35438347]
[0.21345019 1.43094678 4.16811379 ... 0.3851467  2.1050082  3.15585162]
[ 27.35853195  22.7689743   24.05047417 ... -11.05666161 -10.69903374
 -12.15934753]
[0.39505499 2.62912512 7.59973646 ... 3.63498752 4.28407511 3.22040278]
[56.35619164 57.9059124  46.1935997  ... 29.77252007 28.4910202
 28.84864807]
[ 0.81377884  5.57466275 16.53166134 ... -0.78146683 -0.88140407
 -0.4969507

[-11.38448715 -11.62290573  -7.24196434 ...  14.7819519    9.38773155
  10.28180122]
[-0.16439107 -1.12505715 -3.30310374 ...  3.75571523  4.39957681
  5.79290271]
[ -2.29477882   0.14901161   3.51667404 ...  -9.7155571  -12.87460327
 -15.25878906]
[-0.03313642 -0.19079644 -0.38443139 ...  6.83664694  8.53040617
  9.58402149]
[-11.1758709   -8.46385956  -4.529953   ... -13.64946365  -1.37090683
  -4.97698784]
[-0.16137867 -1.06190004 -2.95762184 ...  6.44099901  6.57480523
  7.19832584]
[-3.90410423 -2.98023224 -0.77486038 ...  2.65240669  2.98023224
  3.03983688]
[-0.05637495 -0.37129676 -1.0235121  ...  3.5369219   3.92598333
  5.13034405]
[-15.02037048 -11.41428947  -8.28504562 ... -16.48068428 -15.13957977
 -16.45088196]
[-0.21689293 -1.42775482 -4.0100328  ...  5.70696817  7.95261668
 10.04181646]
[-27.6863575  -20.20597458 -14.36471939 ... -40.11392593 -42.14048386
 -35.88199615]
[-0.39978876 -2.61967964 -7.3083374  ... 11.03431305  9.28878303
  4.23916534]
[-11.83152199  -9.0897

[ -0.61280861  -4.09416731 -11.95350035 ...  10.91059809  11.52003229
  10.30885872]
[  5.36441803   9.00030136   2.05636024 ...   0.11920929  -5.87105751
 -10.49041748]
[0.07746176 0.58101127 1.83311862 ... 6.83873621 5.10624111 4.09576143]
[ 5.27501106  8.76188278  2.74181366 ...  4.35113907 -1.60932541
 -2.86102295]
[ 0.07617073  0.57005106  1.8055255  ...  2.44882431  0.5884079
 -0.58734201]
[-12.72559166  -8.22544098 -14.513731   ...  11.29508018   7.65919685
   6.16908073]
[-0.18375651 -1.18875994 -3.38411076 ...  1.01492498 -1.47440012
 -3.65710865]
[ 2.32458115  6.22868538  0.23841858 ... 19.37150955 16.7787075
 15.37799835]
[ 0.03356676  0.28539569  0.98071498 ... -2.06878717 -4.18671922
 -5.56102101]
[-9.00030136 -3.09944153 -9.86456871 ... 33.97464752 33.76603127
 33.02097321]
[-0.12996362 -0.8015134  -2.15912391 ... -4.42472586 -5.64063911
 -5.5537008 ]
[18.09000969 22.05371857 14.33491707 ... 18.80526543 18.29862595
 16.2422657 ]
[ 0.26121828  1.83948679  5.59089653 ... -6

[-0.08047416 -0.53615225 -1.62667106 ... -0.26286718 -0.07352419
  1.53961267]
[ 0.29802322 -0.98347664 -1.4603138  ... -6.58631325 -1.04308128
 -6.07967377]
[ 0.00430343  0.01085688 -0.0456307  ... -0.85212814 -0.50402134
 -0.33413566]
[-13.02361488 -14.42432404 -14.36471939 ...  14.36471939  15.46740532
  16.18266106]
[-0.18805994 -1.30332951 -3.96131783 ... -1.75205356 -1.17876618
 -1.16649378]
[-7.12275505 -8.5234642  -8.10623169 ... 16.06345177 17.25554466
 17.9708004 ]
[-0.10285201 -0.72196917 -2.22345941 ... -1.53778034 -1.01366727
 -1.0657687 ]
[-19.13309097 -19.78874207 -18.95427704 ...  12.39776611  13.08321953
  11.68251038]
[-0.27628028 -1.89448443 -5.670676   ... -2.11679784 -1.75298125
 -2.34117596]
[-11.80171967 -13.50045204 -13.32163811 ...   9.38773155  12.36796379
  -7.33137131]
[-0.17041588 -1.18725025 -3.63016786 ... -4.49837958 -2.93405068
 -1.5387695 ]
[-15.22898674 -20.47419548 -19.52052116 ...   0.71525574  13.82827759
  31.44145012]
[ -0.21990534  -1.57611987  

[0.08133485 0.54331561 1.5441047  ... 1.63390885 2.90740061 3.91158154]
[  7.89761543   7.92741776   9.00030136 ... -20.38478851 -15.76542854
 -13.94748688]
[ 0.11404093  0.77851363  2.33743857 ... -0.5971733   1.46530024
  3.47812192]
[ 0.5364418   1.16229057  2.02655792 ... -0.86426735  0.29802322
  1.04308128]
[ 0.00774618  0.06188815  0.23165705 ... -0.8870672  -0.68139709
 -0.3179598 ]
[-17.37475395 -19.81854439 -18.83506775 ...  19.60992813  20.08676529
  20.62320709]
[-0.25089004 -1.74707137 -5.32838619 ... -0.28841802  1.13890467
  2.0491301 ]
[10.7884407   9.92417336  7.83801079 ... 11.50369644 12.63618469
 13.85807991]
[0.15578421 1.05041119 3.05258249 ... 0.25301729 2.03338496 2.20417052]
[ 1.07288361 -1.1920929  -2.41398811 ...  1.60932541  2.59280205
  0.11920929]
[0.01549235 0.0729958  0.07424284 ... 1.10856431 2.12848474 1.38226336]
[10.99705696 11.59310341  5.06639481 ... -4.76837158 -9.59634781
 -3.21865082]
[ 0.15879661  1.09205114  3.19359023 ... -2.18845903 -0.86653

[ 0.17945308  1.30055085  4.18177042 ... -0.75467859 -1.82427882
 -3.08566271]
[21.27885818 24.64652061 25.39157867 ... 12.18914986 16.06345177
 14.99056816]
[ 0.30726499  2.14504941  6.59074571 ... -6.48136651 -6.10600501
 -4.49919188]
[39.63708878 42.49811172 44.22664642 ... 16.59989357 21.87490463
 17.88139343]
[ 0.57235635  3.94641021 11.94563675 ... -4.79600403 -4.79247216
 -4.00520588]
[13.50045204 17.10653305 16.30187035 ... 13.58985901 18.2390213
 15.76542854]
[ 0.19494543  1.38215352  4.30785104 ... -8.08342798 -7.04199337
 -4.76050225]
[ 2.68220901  5.54323196  4.05311584 ...  9.65595245 11.62290573
 12.48717308]
[ 0.03873088  0.30556764  1.04794285 ... -5.72098514 -5.65060258
 -4.37915171]
[38.02776337 40.68017006 39.3986702  ... 80.49607277 81.27093315
 82.73124695]
[ 0.54911782  3.78484498 11.40906596 ... -0.91937156 -0.90332819
 -0.5414179 ]
[ 49.41225052  52.21366882  52.30307579 ... 173.33030701 170.20106316
 166.74399376]
[ 0.7135089   4.9086111  14.78641743 ...  4.329

[ -1.46962176 -10.0313013  -29.77367102 ...   2.09456117   1.19235567
   1.67294615]
[-101.68552399 -100.52323341  -87.8572464  ...   89.25795555   85.53266525
   84.25116539]
[ -1.46833073 -10.001406   -29.5609421  ...  12.73959435  11.83658542
   3.58118454]
[-38.98143768 -39.75629807 -30.45797348 ...  86.81416512  85.41345596
  82.91006088]
[ -0.5628888   -3.85169059 -11.38835677 ...  11.49323832  10.87457748
   4.31929969]
[-59.69405174 -61.03515625 -52.06465721 ... 142.09747314 138.5807991
 138.19336891]
[ -0.86197727  -5.90050065 -17.53080967 ...   8.15772666   8.45113799
   4.98246613]
[-62.46566772 -63.24052811 -51.76663399 ... 135.39195061 134.8555088
 134.70649719]
[ -0.90199918  -6.16538732 -18.25271501 ...   4.16044902   3.85966835
   2.75833654]
[-200.2120018  -200.15239716 -181.61535263 ...  179.40998077  178.45630646
  178.72452736]
[ -2.8910451  -19.72428476 -58.51554682 ...   6.93918873   6.65327357
   5.53290498]
[ 16.12305641  23.63324165  35.73298454 ... -50.6341457

[ 0.10371269  0.79798743  2.83574865 ... -2.33280075 -2.25688781
 -0.70302366]
[ -5.39422035  -5.69224358  -3.09944153 ... -22.73917198 -20.98083496
 -19.46091652]
[-0.07789211 -0.535749   -1.5758494  ... -4.85620653 -4.58892511
 -3.57863615]
[-14.39452171 -17.1661377  -13.05341721 ... -20.80202103 -14.7819519
 -12.5169754 ]
[-0.20785573 -1.45818881 -4.44039982 ... -6.01294281 -6.35345122
 -5.49351477]
[ -7.39097595 -10.49041748   2.02655792 ... -37.07408905 -29.05726433
 -28.58042717]
[ -0.10672509  -0.7729242   -2.29486025 ...  -5.56931979  -9.31837262
 -11.31161603]
[  9.08970833   6.64591789   5.09619713 ... -33.22958946 -26.94129944
 -26.88169479]
[ 0.13125465  0.86024169  2.40590607 ... -0.4227017  -4.85946627
 -4.31625471]
[  1.01327896  -1.60932541  -5.27501106 ... -19.75893974 -14.39452171
 -15.73562622]
[ 0.01463167  0.06195936 -0.01378121 ...  0.28058978 -3.82171788
 -4.00458762]
[18.38803291 14.75214958 13.91768456 ... -3.12924385  0.47683716
 -0.5364418 ]
[ 0.26552171  1.7

[0.18246548 1.18210317 3.29593756 ... 4.64928055 7.37427616 6.09803923]
[29.951334   18.89467239 20.44439316 ... 34.03425217 40.85898399
 37.16349602]
[0.43249484 2.79118688 7.72779747 ... 0.98374576 4.74669503 6.86640909]
[29.26588058 19.46091652 20.62320709 ... 33.58721733 40.59076309
 36.26942635]
[0.42259695 2.74172953 7.6442493  ... 1.26979301 5.13972336 7.27934678]
[22.05371857 19.60992813 18.74566078 ... 33.52761269 40.08412361
 33.43820572]
[ 0.31845391  2.13747275  6.22248084 ...  3.51513518  1.58677737
 -0.51852032]
[22.26233482 19.13309097 19.58012581 ... 33.4084034  40.35234451
 33.19978714]
[0.32146631 2.148128   6.23514105 ... 3.58094351 1.91030973 0.05264182]
[18.26882362 17.37475395 16.74890518 ... 13.7090683  19.81854439
 13.32163811]
[0.26380033 1.78695785 5.26722945 ... 6.5228676  4.76229754 1.59784324]
[13.61966133 13.58985901 12.18914986 ...  4.23192978  8.64267349
  4.82797623]
[0.19666681 1.34139631 3.97603618 ... 5.35567483 5.75679813 2.63371859]
[19.46091652 16

[-0.16180901 -1.03858527 -2.84665421 ... -1.4769682  -0.13963589
  0.79750154]
[ 9.89437103 13.82827759 14.90116119 ... 12.06994057  4.73856926
  6.85453415]
[ 0.14287392  1.03161153  3.30839172 ... -1.99325342 -0.83988205
 -0.0398914 ]
[10.04338264 13.61966133 14.18590546 ... 13.38124275  5.7220459
  7.77840614]
[ 0.14502563  1.04112823  3.30959683 ... -2.08063528 -1.05735329
 -0.42541522]
[12.36796379 11.08646393 10.01358032 ...  2.89082527 -7.24196434
 -3.96370888]
[ 0.1785924   1.20000304  3.48990988 ...  1.55991766  0.95439094
 -1.15936533]
[ -1.43051147  -5.27501106   2.86102295 ... -12.75539398 -14.99056816
 -12.54677773]
[-0.02065647 -0.1964501  -0.6813285  ...  2.45579477  4.12099198
  4.24899473]
[17.73238182 12.18914986 17.1661377  ... -6.04987144 -8.7916851
 -6.40749931]
[0.25605416 1.66697338 4.73257481 ... 5.20719276 6.30813381 5.0184738 ]
[17.9708004  12.30835915 16.80850983 ... -5.57303429 -8.04662704
 -6.73532486]
[0.2594969  1.68874131 4.78395252 ... 5.22178334 6.4025

[ 0.19322406  1.28907402  3.76912308 ... -3.09291295 -1.60109913
 -0.07395441]
[  6.73532486   4.41074371   8.16583633 ... -22.53055573 -22.94778824
 -19.75893974]
[ 0.09725755  0.63000616  1.80292427 ... -1.41874364 -0.4097554
  0.64922616]
[ 2.17556953 -2.05636024  0.89406967 ...  1.01327896 -1.51991844
  1.57952309]
[ 0.03141505  0.1532312   0.26449041 ...  0.3940938   0.29440901
 -0.03206665]
[-12.21895218 -15.52700996 -11.20567322 ...  22.41134644  20.29538155
  23.18620682]
[-0.17644068 -1.25159506 -3.85141673 ... -1.33036764 -1.71238692
 -1.90696667]
[ -8.76188278 -12.01033592  -9.29832458 ...  27.26912498  26.13663673
  29.6831131 ]
[-0.12652088 -0.91013943 -2.85366909 ... -2.45045429 -2.10932434
 -1.82018083]
[-2.98023224e-02 -7.15255737e-01  6.85453415e-01 ...  5.23924828e+01
  5.03659248e+01  5.45680523e+01]
[-4.30343122e-04 -1.28340552e-02 -5.60566118e-02 ... -2.04829210e+00
 -1.84912485e+00 -1.89115867e+00]
[12.48717308 18.92447472 18.06020737 ... -1.57952309 -2.89082527
 

the shape of segments is: (41000, 62)
the shape of labels_one is: (41,)
the shape of segments is: (47000, 62)
the shape of labels_one is: (47,)
the shape of segments is: (47000, 62)
the shape of labels_one is: (47,)
the shape of segments is: (46000, 62)
the shape of labels_one is: (46,)
the shape of segments is: (41000, 62)
the shape of labels_one is: (41,)
the shape of segments is: (41000, 62)
the shape of labels_one is: (41,)
the shape of segments is: (47000, 62)
the shape of labels_one is: (47,)
the shape of segments is: (47000, 62)
the shape of labels_one is: (47,)
the shape of segments is: (46000, 62)
the shape of labels_one is: (46,)
the shape of segments is: (41000, 62)
the shape of labels_one is: (41,)
the shape of segments is: (41000, 62)
the shape of labels_one is: (41,)
the shape of segments is: (47000, 62)
the shape of labels_one is: (47,)
the shape of segments is: (47000, 62)
the shape of labels_one is: (47,)
the shape of segments is: (46000, 62)
the shape of labels_one is